In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns

import warnings
warnings.filterwarnings("ignore")

In [2]:
pcf_gen = pd.read_csv("./Data/pcf-general.csv")

In [3]:
pcf_gen

,AuthorID,Author,Date,Content,Attachments,Reactions
0,265899192373870592,KaiaLou#7681,20-May-18 08:00 AM,Anyone played Chapters?,NaN,NaN
1,292140230729924608,Kaii#9972,20-May-18 08:00 AM,Yeah,NaN,NaN
2,265899192373870592,KaiaLou#7681,20-May-18 08:02 AM,This peep said one time about the diamonds...,NaN,NaN
3,265899192373870592,KaiaLou#7681,20-May-18 08:02 AM,*walk away* - costs diamonds \r\n*insult her m...,NaN,NaN
4,292140230729924608,Kaii#9972,20-May-18 08:02 AM,LOLL,NaN,NaN
...,...,...,...,...,...,...
356946,692342743418142801,ùôÅùôûùôßùôöùô¨ùô§ùôßùô†#2551,26-Sep-22 12:00 PM,you should look at the abs,NaN,NaN
356947,310882928752328735,Belbercike#4557,26-Sep-22 12:31 PM,"to compensate, his waist isn't snatched",NaN,NaN
356948,301372241176952832,azula#9750,26-Sep-22 12:49 PM,Stepped in a puddle and ruined my AF1s my day ...,https://cdn.discordapp.com/attachments/4475818...,NaN
356949,301372241176952832,azula#9750,26-Sep-22 12:50 PM,Now one is clean and one isn't,https://cdn.discordapp.com/attachments/4475818...,NaN
356950,397356894127390720,Rayvenrock#2954,26-Sep-22 01:44 PM,nuuuu],NaN,NaN

In [4]:
df1 = pd.DataFrame(pcf_gen)

In [5]:
df1

,AuthorID,Author,Date,Content,Attachments,Reactions
0,265899192373870592,KaiaLou#7681,20-May-18 08:00 AM,Anyone played Chapters?,NaN,NaN
1,292140230729924608,Kaii#9972,20-May-18 08:00 AM,Yeah,NaN,NaN
2,265899192373870592,KaiaLou#7681,20-May-18 08:02 AM,This peep said one time about the diamonds...,NaN,NaN
3,265899192373870592,KaiaLou#7681,20-May-18 08:02 AM,*walk away* - costs diamonds \r\n*insult her m...,NaN,NaN
4,292140230729924608,Kaii#9972,20-May-18 08:02 AM,LOLL,NaN,NaN
...,...,...,...,...,...,...
356946,692342743418142801,ùôÅùôûùôßùôöùô¨ùô§ùôßùô†#2551,26-Sep-22 12:00 PM,you should look at the abs,NaN,NaN
356947,310882928752328735,Belbercike#4557,26-Sep-22 12:31 PM,"to compensate, his waist isn't snatched",NaN,NaN
356948,301372241176952832,azula#9750,26-Sep-22 12:49 PM,Stepped in a puddle and ruined my AF1s my day ...,https://cdn.discordapp.com/attachments/4475818...,NaN
356949,301372241176952832,azula#9750,26-Sep-22 12:50 PM,Now one is clean and one isn't,https://cdn.discordapp.com/attachments/4475818...,NaN
356950,397356894127390720,Rayvenrock#2954,26-Sep-22 01:44 PM,nuuuu],NaN,NaN

In [6]:
df1 = df1.drop(['Attachments', 'Reactions'], axis=1)

In [7]:
df1

,AuthorID,Author,Date,Content
0,265899192373870592,KaiaLou#7681,20-May-18 08:00 AM,Anyone played Chapters?
1,292140230729924608,Kaii#9972,20-May-18 08:00 AM,Yeah
2,265899192373870592,KaiaLou#7681,20-May-18 08:02 AM,This peep said one time about the diamonds...
3,265899192373870592,KaiaLou#7681,20-May-18 08:02 AM,*walk away* - costs diamonds \r\n*insult her m...
4,292140230729924608,Kaii#9972,20-May-18 08:02 AM,LOLL
...,...,...,...,...
356946,692342743418142801,ùôÅùôûùôßùôöùô¨ùô§ùôßùô†#2551,26-Sep-22 12:00 PM,you should look at the abs
356947,310882928752328735,Belbercike#4557,26-Sep-22 12:31 PM,"to compensate, his waist isn't snatched"
356948,301372241176952832,azula#9750,26-Sep-22 12:49 PM,Stepped in a puddle and ruined my AF1s my day ...
356949,301372241176952832,azula#9750,26-Sep-22 12:50 PM,Now one is clean and one isn't
356950,397356894127390720,Rayvenrock#2954,26-Sep-22 01:44 PM,nuuuu]

In [8]:
new_df1 = df1.groupby("AuthorID").agg(lambda x:x.tolist())

In [9]:
new_df1

,Author,Date,Content
AuthorID,,,
83707600847241216,"[nekopon#2749, nekopon#2749, nekopon#2749, nek...","[19-May-19 02:39 AM, 19-May-19 02:45 AM, 19-Ma...",[Hi! I'm new to Choices... Really enjoying WT ...
85614143951892480,"[UB3R-B0T#3802, UB3R-B0T#3802, UB3R-B0T#3802, ...","[04-Jul-18 09:37 AM, 04-Jul-18 09:37 AM, 04-Ju...",[woah there buttmunch tryin' to cheat the syst...
89748521887997952,"[Blattella#4913, Blattella#4913, Blattella#491...","[02-Feb-19 05:38 PM, 06-Apr-19 01:03 AM, 06-Ap...","[nan, What‚Äôs up everybody I think dogs should ..."
105918316341628928,"[·πú…õ’º√∏üåô#0101, ·πú…õ’º√∏üåô#0101]","[21-Sep-18 11:04 PM, 22-Sep-18 09:59 AM]","[https://www.youtube.com/watch?v=GpCIWJBS47k, üåö]"
106634422022860800,"[MaralinaSakura#1304, MaralinaSakura#1304, Mar...","[03-Apr-19 09:50 PM, 03-Apr-19 09:50 PM, 03-Ap...","[:javoShock: I got to think about it, Thanks!,..."
...,...,...,...
873569055733329951,[James Hametson#9998],[12-Aug-21 03:55 PM],[Where‚Äôs the invite to the datamining server a...
899901520701714493,"[Kaleen Bhaiya#5212, Kaleen Bhaiya#5212, Kalee...","[21-Oct-21 01:46 PM, 21-Oct-21 01:48 PM, 21-Oc...","[that chapter was so boring, not really becaus..."
936271044292001873,"[Luany#5229, Luany#5229, Luany#5229, Luany#522...","[02-Sep-22 11:00 PM, 10-Sep-22 07:09 AM, 10-Se...",[My friend says it's [making someone] with an ...
957682000360255488,"[Sneaky Shadows#1096, Sneaky Shadows#1096, Sne...","[24-Sep-22 12:22 AM, 24-Sep-22 12:24 AM, 24-Se...","[Hi everyone!, My friends usually call me Shad..."
971183631928279110,[lexddy#7990],[12-Sep-22 07:19 AM],[Hi]

In [12]:
spl_gen_1 = pd.read_csv("./Data/spl-gen-1.csv")
spl_gen_2 = pd.read_csv("./Data/spl-gen-2.csv")

In [13]:
spl_gen = pd.concat([spl_gen_1, spl_gen_2], axis=0, ignore_index=True)

In [14]:
spl_gen

,AuthorID,Author,Date,Content,Attachments,Reactions
0,495167666726895616,( À∂·µî‡ºù·µîÀ∂) milquetoast ‚ô°#1999,05-Sep-20 12:35 AM,HELLO thank you for inviting and accepting me!!!,NaN,NaN
1,442393544376975380,Raven#5888,05-Sep-20 12:35 AM,ü§ó,NaN,NaN
2,495167666726895616,( À∂·µî‡ºù·µîÀ∂) milquetoast ‚ô°#1999,05-Sep-20 12:35 AM,wow it‚Äôs just like the old server üò≥,NaN,NaN
3,362299347729121281,Brohepsi#1599,05-Sep-20 12:41 AM,Thanks for doing this so much. You've made my ...,NaN,NaN
4,692342743418142801,ùôÅùôûùôßùôöùô¨ùô§ùôßùô†#2551,05-Sep-20 12:41 AM,I'm glad to hear it.,NaN,NaN
...,...,...,...,...,...,...
94802,106634422022860800,MaralinaSakura#1304,25-Sep-22 02:02 AM,Like early 40s at *worst*,NaN,NaN
94803,707303192257626164,Metta#2122,25-Sep-22 05:35 AM,oh hey another TCH ad by PB,https://cdn.discordapp.com/attachments/7514700...,NaN
94804,495167666726895616,( À∂·µî‡ºù·µîÀ∂) milquetoast ‚ô°#1999,25-Sep-22 07:03 AM,I thought tch2 :pepesadboi:,NaN,NaN
94805,707303192257626164,Metta#2122,25-Sep-22 07:07 AM,Soon enough,NaN,NaN
94806,757599193614254141,Akuna Matata#7251,25-Sep-22 10:47 AM,~~*seals the curse instead*~~,NaN,NaN

In [15]:
df2 = pd.DataFrame(spl_gen)

In [16]:
df2

,AuthorID,Author,Date,Content,Attachments,Reactions
0,495167666726895616,( À∂·µî‡ºù·µîÀ∂) milquetoast ‚ô°#1999,05-Sep-20 12:35 AM,HELLO thank you for inviting and accepting me!!!,NaN,NaN
1,442393544376975380,Raven#5888,05-Sep-20 12:35 AM,ü§ó,NaN,NaN
2,495167666726895616,( À∂·µî‡ºù·µîÀ∂) milquetoast ‚ô°#1999,05-Sep-20 12:35 AM,wow it‚Äôs just like the old server üò≥,NaN,NaN
3,362299347729121281,Brohepsi#1599,05-Sep-20 12:41 AM,Thanks for doing this so much. You've made my ...,NaN,NaN
4,692342743418142801,ùôÅùôûùôßùôöùô¨ùô§ùôßùô†#2551,05-Sep-20 12:41 AM,I'm glad to hear it.,NaN,NaN
...,...,...,...,...,...,...
94802,106634422022860800,MaralinaSakura#1304,25-Sep-22 02:02 AM,Like early 40s at *worst*,NaN,NaN
94803,707303192257626164,Metta#2122,25-Sep-22 05:35 AM,oh hey another TCH ad by PB,https://cdn.discordapp.com/attachments/7514700...,NaN
94804,495167666726895616,( À∂·µî‡ºù·µîÀ∂) milquetoast ‚ô°#1999,25-Sep-22 07:03 AM,I thought tch2 :pepesadboi:,NaN,NaN
94805,707303192257626164,Metta#2122,25-Sep-22 07:07 AM,Soon enough,NaN,NaN
94806,757599193614254141,Akuna Matata#7251,25-Sep-22 10:47 AM,~~*seals the curse instead*~~,NaN,NaN

In [17]:
df2 = df2.drop(['Attachments', 'Reactions'], axis=1)

In [18]:
df2

,AuthorID,Author,Date,Content
0,495167666726895616,( À∂·µî‡ºù·µîÀ∂) milquetoast ‚ô°#1999,05-Sep-20 12:35 AM,HELLO thank you for inviting and accepting me!!!
1,442393544376975380,Raven#5888,05-Sep-20 12:35 AM,ü§ó
2,495167666726895616,( À∂·µî‡ºù·µîÀ∂) milquetoast ‚ô°#1999,05-Sep-20 12:35 AM,wow it‚Äôs just like the old server üò≥
3,362299347729121281,Brohepsi#1599,05-Sep-20 12:41 AM,Thanks for doing this so much. You've made my ...
4,692342743418142801,ùôÅùôûùôßùôöùô¨ùô§ùôßùô†#2551,05-Sep-20 12:41 AM,I'm glad to hear it.
...,...,...,...,...
94802,106634422022860800,MaralinaSakura#1304,25-Sep-22 02:02 AM,Like early 40s at *worst*
94803,707303192257626164,Metta#2122,25-Sep-22 05:35 AM,oh hey another TCH ad by PB
94804,495167666726895616,( À∂·µî‡ºù·µîÀ∂) milquetoast ‚ô°#1999,25-Sep-22 07:03 AM,I thought tch2 :pepesadboi:
94805,707303192257626164,Metta#2122,25-Sep-22 07:07 AM,Soon enough
94806,757599193614254141,Akuna Matata#7251,25-Sep-22 10:47 AM,~~*seals the curse instead*~~

In [19]:
new_df2 = df2.groupby("AuthorID").agg(lambda x:x.tolist())

In [20]:
new_df2

,Author,Date,Content
AuthorID,,,
85614143951892480,"[UB3R-B0T#3802, UB3R-B0T#3802, UB3R-B0T#3802, ...","[07-Sep-20 11:02 PM, 07-Sep-20 11:06 PM, 07-Se...","[cool cool cool, cool cool cool, T_T, I know.,..."
106634422022860800,"[MaralinaSakura#1304, MaralinaSakura#1304, Mar...","[05-Sep-20 12:44 AM, 05-Sep-20 12:44 AM, 05-Se...","[:CatriaYay:, Just ask one of us what you want..."
137010219573182464,"[Pokechu#3436, Pokechu#3436, Pokechu#3436, Pok...","[17-Nov-21 04:12 AM, 17-Nov-21 04:13 AM, 17-No...","[is there no channel for shipwrecked ?, LOL sh..."
155149108183695360,"[Dyno#3861, Dyno#3861, Dyno#3861, Dyno#3861, D...","[03-Oct-20 04:07 AM, 04-Oct-20 09:30 PM, 04-Oc...","[Its Baby Dump without a Bump (BD), Its Baby D..."
172002275412279296,"[Tatsu#8792, Tatsu#8792, Tatsu#8792, Tatsu#879...","[05-Sep-20 12:56 AM, 05-Sep-20 02:03 AM, 05-Se...","[nan, nan, nan, nan, > **‚ÄéViewing rank card ‚Ä¢..."
...,...,...,...
873569055733329951,"[James Hametson#9998, James Hametson#9998, Jam...","[14-Aug-21 07:55 PM, 14-Aug-21 07:55 PM, 22-Au...","[I don‚Äôt know, Lo, Tomorrow my birthday, The o..."
875621667680972851,"[monsoonwinds#0471, monsoonwinds#0471, monsoon...","[10-Dec-21 05:00 AM, 10-Dec-21 05:01 AM, 10-De...","[Is anyone else going through finals week?, Ye..."
899901520701714493,"[Kaleen Bhaiya#5212, Kaleen Bhaiya#5212, Kalee...","[21-Oct-21 01:52 PM, 21-Oct-21 01:53 PM, 23-Oc...","[MM/DD/YY goes to #üîûcursed-chat, :angydoggo:, ..."
906809341968007189,[Silent Salina#6193],[21-Nov-21 04:19 PM],[:pixelbartie: omg this exists]
952791904888692796,"[Angel Savage's Wife#3077, Angel Savage's Wife...","[14-Mar-22 12:20 PM, 15-Mar-22 12:40 PM, 15-Ma...","[Rip 1 hour of my sleep, Is it the same for ev..."

In [21]:
common = new_df1.merge(new_df2, on=["AuthorID"])

In [22]:
common

,Author_x,Date_x,Content_x,Author_y,Date_y,Content_y
AuthorID,,,,,,
85614143951892480,"[UB3R-B0T#3802, UB3R-B0T#3802, UB3R-B0T#3802, ...","[04-Jul-18 09:37 AM, 04-Jul-18 09:37 AM, 04-Ju...",[woah there buttmunch tryin' to cheat the syst...,"[UB3R-B0T#3802, UB3R-B0T#3802, UB3R-B0T#3802, ...","[07-Sep-20 11:02 PM, 07-Sep-20 11:06 PM, 07-Se...","[cool cool cool, cool cool cool, T_T, I know.,..."
106634422022860800,"[MaralinaSakura#1304, MaralinaSakura#1304, Mar...","[03-Apr-19 09:50 PM, 03-Apr-19 09:50 PM, 03-Ap...","[:javoShock: I got to think about it, Thanks!,...","[MaralinaSakura#1304, MaralinaSakura#1304, Mar...","[05-Sep-20 12:44 AM, 05-Sep-20 12:44 AM, 05-Se...","[:CatriaYay:, Just ask one of us what you want..."
155149108183695360,"[Dyno#3861, Dyno#3861, Dyno#3861, Dyno#3861, D...","[14-Dec-18 03:34 PM, 14-Dec-18 03:35 PM, 07-Ja...","[nan, nan, Wife: Honey I‚Äôm pregnant.\r\n\r\nMe...","[Dyno#3861, Dyno#3861, Dyno#3861, Dyno#3861, D...","[03-Oct-20 04:07 AM, 04-Oct-20 09:30 PM, 04-Oc...","[Its Baby Dump without a Bump (BD), Its Baby D..."
172002275412279296,"[Tatsu#8792, Tatsu#8792, Tatsu#8792, Tatsu#879...","[23-Feb-21 09:15 PM, 25-Feb-21 11:23 PM, 08-Ma...","[nan, nan, nan, > **Viewing server rankings ‚Ä¢ ...","[Tatsu#8792, Tatsu#8792, Tatsu#8792, Tatsu#879...","[05-Sep-20 12:56 AM, 05-Sep-20 02:03 AM, 05-Se...","[nan, nan, nan, nan, > **‚ÄéViewing rank card ‚Ä¢..."
173889000015134720,"[faede#0003, faede#0003, faede#0003, faede#000...","[30-Jul-20 01:07 AM, 30-Jul-20 01:08 AM, 30-Ju...",[uhh dskdjdl probably high school story and mi...,"[faede#0003, faede#0003, faede#0003, faede#000...","[07-Sep-20 10:37 AM, 07-Sep-20 10:39 AM, 07-Se...","[omg hana my love, i go for both yea, tru, Thi..."
...,...,...,...,...,...,...
786672447935348737,"[cressidastclaire#3536, cressidastclaire#3536,...","[05-May-21 11:35 AM, 05-May-21 12:21 PM, 05-Ma...","[hello! glad to be here., pig practicals in bi...","[cressidastclaire#3536, cressidastclaire#3536,...","[06-May-21 11:48 PM, 06-May-21 11:57 PM, 06-Ma...","[... what. that's a joke, right?, If that's tr..."
806489789574545458,[Hell-Volhard#4976],[18-Apr-21 09:38 PM],"[sure, thanks]",[Hell-Volhard#4976],[07-Aug-21 07:32 PM],[Same lol]
831172293945720852,"[Yume Not.#8543, Yume Not.#8543, Yume Not.#854...","[28-Apr-21 10:22 AM, 28-Apr-21 10:23 AM, 28-Ap...","[Hiiiiiii, And we may or may not regret it lol...","[Yume Not.#8543, Yume Not.#8543, Yume Not.#854...","[21-Aug-21 04:01 PM, 25-Aug-21 11:29 AM, 25-Au...","[I love the channel namesssss, Whoa... This is..."
873569055733329951,[James Hametson#9998],[12-Aug-21 03:55 PM],[Where‚Äôs the invite to the datamining server a...,"[James Hametson#9998, James Hametson#9998, Jam...","[14-Aug-21 07:55 PM, 14-Aug-21 07:55 PM, 22-Au...","[I don‚Äôt know, Lo, Tomorrow my birthday, The o..."
899901520701714493,"[Kaleen Bhaiya#5212, Kaleen Bhaiya#5212, Kalee...","[21-Oct-21 01:46 PM, 21-Oct-21 01:48 PM, 21-Oc...","[that chapter was so boring, not really becaus...","[Kaleen Bhaiya#5212, Kaleen Bhaiya#5212, Kalee...","[21-Oct-21 01:52 PM, 21-Oct-21 01:53 PM, 23-Oc...","[MM/DD/YY goes to #üîûcursed-chat, :angydoggo:, ..."

In [23]:
pcf_gen_common = common.drop(["Author_y","Content_y","Date_y"], axis = 1)

In [24]:
pcf_gen_common

,Author_x,Date_x,Content_x
AuthorID,,,
85614143951892480,"[UB3R-B0T#3802, UB3R-B0T#3802, UB3R-B0T#3802, ...","[04-Jul-18 09:37 AM, 04-Jul-18 09:37 AM, 04-Ju...",[woah there buttmunch tryin' to cheat the syst...
106634422022860800,"[MaralinaSakura#1304, MaralinaSakura#1304, Mar...","[03-Apr-19 09:50 PM, 03-Apr-19 09:50 PM, 03-Ap...","[:javoShock: I got to think about it, Thanks!,..."
155149108183695360,"[Dyno#3861, Dyno#3861, Dyno#3861, Dyno#3861, D...","[14-Dec-18 03:34 PM, 14-Dec-18 03:35 PM, 07-Ja...","[nan, nan, Wife: Honey I‚Äôm pregnant.\r\n\r\nMe..."
172002275412279296,"[Tatsu#8792, Tatsu#8792, Tatsu#8792, Tatsu#879...","[23-Feb-21 09:15 PM, 25-Feb-21 11:23 PM, 08-Ma...","[nan, nan, nan, > **Viewing server rankings ‚Ä¢ ..."
173889000015134720,"[faede#0003, faede#0003, faede#0003, faede#000...","[30-Jul-20 01:07 AM, 30-Jul-20 01:08 AM, 30-Ju...",[uhh dskdjdl probably high school story and mi...
...,...,...,...
786672447935348737,"[cressidastclaire#3536, cressidastclaire#3536,...","[05-May-21 11:35 AM, 05-May-21 12:21 PM, 05-Ma...","[hello! glad to be here., pig practicals in bi..."
806489789574545458,[Hell-Volhard#4976],[18-Apr-21 09:38 PM],"[sure, thanks]"
831172293945720852,"[Yume Not.#8543, Yume Not.#8543, Yume Not.#854...","[28-Apr-21 10:22 AM, 28-Apr-21 10:23 AM, 28-Ap...","[Hiiiiiii, And we may or may not regret it lol..."
873569055733329951,[James Hametson#9998],[12-Aug-21 03:55 PM],[Where‚Äôs the invite to the datamining server a...
899901520701714493,"[Kaleen Bhaiya#5212, Kaleen Bhaiya#5212, Kalee...","[21-Oct-21 01:46 PM, 21-Oct-21 01:48 PM, 21-Oc...","[that chapter was so boring, not really becaus..."

In [25]:
spf_gen_common = common.drop(["Author_x","Content_x","Date_x"], axis = 1)

In [26]:
spf_gen_common

,Author_y,Date_y,Content_y
AuthorID,,,
85614143951892480,"[UB3R-B0T#3802, UB3R-B0T#3802, UB3R-B0T#3802, ...","[07-Sep-20 11:02 PM, 07-Sep-20 11:06 PM, 07-Se...","[cool cool cool, cool cool cool, T_T, I know.,..."
106634422022860800,"[MaralinaSakura#1304, MaralinaSakura#1304, Mar...","[05-Sep-20 12:44 AM, 05-Sep-20 12:44 AM, 05-Se...","[:CatriaYay:, Just ask one of us what you want..."
155149108183695360,"[Dyno#3861, Dyno#3861, Dyno#3861, Dyno#3861, D...","[03-Oct-20 04:07 AM, 04-Oct-20 09:30 PM, 04-Oc...","[Its Baby Dump without a Bump (BD), Its Baby D..."
172002275412279296,"[Tatsu#8792, Tatsu#8792, Tatsu#8792, Tatsu#879...","[05-Sep-20 12:56 AM, 05-Sep-20 02:03 AM, 05-Se...","[nan, nan, nan, nan, > **‚ÄéViewing rank card ‚Ä¢..."
173889000015134720,"[faede#0003, faede#0003, faede#0003, faede#000...","[07-Sep-20 10:37 AM, 07-Sep-20 10:39 AM, 07-Se...","[omg hana my love, i go for both yea, tru, Thi..."
...,...,...,...
786672447935348737,"[cressidastclaire#3536, cressidastclaire#3536,...","[06-May-21 11:48 PM, 06-May-21 11:57 PM, 06-Ma...","[... what. that's a joke, right?, If that's tr..."
806489789574545458,[Hell-Volhard#4976],[07-Aug-21 07:32 PM],[Same lol]
831172293945720852,"[Yume Not.#8543, Yume Not.#8543, Yume Not.#854...","[21-Aug-21 04:01 PM, 25-Aug-21 11:29 AM, 25-Au...","[I love the channel namesssss, Whoa... This is..."
873569055733329951,"[James Hametson#9998, James Hametson#9998, Jam...","[14-Aug-21 07:55 PM, 14-Aug-21 07:55 PM, 22-Au...","[I don‚Äôt know, Lo, Tomorrow my birthday, The o..."
899901520701714493,"[Kaleen Bhaiya#5212, Kaleen Bhaiya#5212, Kalee...","[21-Oct-21 01:52 PM, 21-Oct-21 01:53 PM, 23-Oc...","[MM/DD/YY goes to #üîûcursed-chat, :angydoggo:, ..."

In [27]:
pcf_gen_common["Author"] = [l[0] for l in pcf_gen_common["Author_x"]]

In [29]:
pcf_gen_common.drop(['Author_x'], axis = 1)

,Date_x,Content_x,Author
AuthorID,,,
85614143951892480,"[04-Jul-18 09:37 AM, 04-Jul-18 09:37 AM, 04-Ju...",[woah there buttmunch tryin' to cheat the syst...,UB3R-B0T#3802
106634422022860800,"[03-Apr-19 09:50 PM, 03-Apr-19 09:50 PM, 03-Ap...","[:javoShock: I got to think about it, Thanks!,...",MaralinaSakura#1304
155149108183695360,"[14-Dec-18 03:34 PM, 14-Dec-18 03:35 PM, 07-Ja...","[nan, nan, Wife: Honey I‚Äôm pregnant.\r\n\r\nMe...",Dyno#3861
172002275412279296,"[23-Feb-21 09:15 PM, 25-Feb-21 11:23 PM, 08-Ma...","[nan, nan, nan, > **Viewing server rankings ‚Ä¢ ...",Tatsu#8792
173889000015134720,"[30-Jul-20 01:07 AM, 30-Jul-20 01:08 AM, 30-Ju...",[uhh dskdjdl probably high school story and mi...,faede#0003
...,...,...,...
786672447935348737,"[05-May-21 11:35 AM, 05-May-21 12:21 PM, 05-Ma...","[hello! glad to be here., pig practicals in bi...",cressidastclaire#3536
806489789574545458,[18-Apr-21 09:38 PM],"[sure, thanks]",Hell-Volhard#4976
831172293945720852,"[28-Apr-21 10:22 AM, 28-Apr-21 10:23 AM, 28-Ap...","[Hiiiiiii, And we may or may not regret it lol...",Yume Not.#8543
873569055733329951,[12-Aug-21 03:55 PM],[Where‚Äôs the invite to the datamining server a...,James Hametson#9998
899901520701714493,"[21-Oct-21 01:46 PM, 21-Oct-21 01:48 PM, 21-Oc...","[that chapter was so boring, not really becaus...",Kaleen Bhaiya#5212

In [30]:
spf_gen_common["Author"] = [l[0] for l in spf_gen_common["Author_y"]]

In [31]:
spf_gen_common.drop(["Author_y"], axis = 1)

,Date_y,Content_y,Author
AuthorID,,,
85614143951892480,"[07-Sep-20 11:02 PM, 07-Sep-20 11:06 PM, 07-Se...","[cool cool cool, cool cool cool, T_T, I know.,...",UB3R-B0T#3802
106634422022860800,"[05-Sep-20 12:44 AM, 05-Sep-20 12:44 AM, 05-Se...","[:CatriaYay:, Just ask one of us what you want...",MaralinaSakura#1304
155149108183695360,"[03-Oct-20 04:07 AM, 04-Oct-20 09:30 PM, 04-Oc...","[Its Baby Dump without a Bump (BD), Its Baby D...",Dyno#3861
172002275412279296,"[05-Sep-20 12:56 AM, 05-Sep-20 02:03 AM, 05-Se...","[nan, nan, nan, nan, > **‚ÄéViewing rank card ‚Ä¢...",Tatsu#8792
173889000015134720,"[07-Sep-20 10:37 AM, 07-Sep-20 10:39 AM, 07-Se...","[omg hana my love, i go for both yea, tru, Thi...",faede#0003
...,...,...,...
786672447935348737,"[06-May-21 11:48 PM, 06-May-21 11:57 PM, 06-Ma...","[... what. that's a joke, right?, If that's tr...",cressidastclaire#3536
806489789574545458,[07-Aug-21 07:32 PM],[Same lol],Hell-Volhard#4976
831172293945720852,"[21-Aug-21 04:01 PM, 25-Aug-21 11:29 AM, 25-Au...","[I love the channel namesssss, Whoa... This is...",Yume Not.#8543
873569055733329951,"[14-Aug-21 07:55 PM, 14-Aug-21 07:55 PM, 22-Au...","[I don‚Äôt know, Lo, Tomorrow my birthday, The o...",James Hametson#9998
899901520701714493,"[21-Oct-21 01:52 PM, 21-Oct-21 01:53 PM, 23-Oc...","[MM/DD/YY goes to #üîûcursed-chat, :angydoggo:, ...",Kaleen Bhaiya#5212

In [32]:
pcf_gen_common.drop(["Date_x", "Author_x"],axis = 1)

,Content_x,Author
AuthorID,,
85614143951892480,[woah there buttmunch tryin' to cheat the syst...,UB3R-B0T#3802
106634422022860800,"[:javoShock: I got to think about it, Thanks!,...",MaralinaSakura#1304
155149108183695360,"[nan, nan, Wife: Honey I‚Äôm pregnant.\r\n\r\nMe...",Dyno#3861
172002275412279296,"[nan, nan, nan, > **Viewing server rankings ‚Ä¢ ...",Tatsu#8792
173889000015134720,[uhh dskdjdl probably high school story and mi...,faede#0003
...,...,...
786672447935348737,"[hello! glad to be here., pig practicals in bi...",cressidastclaire#3536
806489789574545458,"[sure, thanks]",Hell-Volhard#4976
831172293945720852,"[Hiiiiiii, And we may or may not regret it lol...",Yume Not.#8543
873569055733329951,[Where‚Äôs the invite to the datamining server a...,James Hametson#9998
899901520701714493,"[that chapter was so boring, not really becaus...",Kaleen Bhaiya#5212

In [33]:
pcf_gen_common["Content"] = [",".join(map(str, l)) for l in pcf_gen_common["Content_x"]]

In [34]:
pcf_gen_common

,Author_x,Date_x,Content_x,Author,Content
AuthorID,,,,,
85614143951892480,"[UB3R-B0T#3802, UB3R-B0T#3802, UB3R-B0T#3802, ...","[04-Jul-18 09:37 AM, 04-Jul-18 09:37 AM, 04-Ju...",[woah there buttmunch tryin' to cheat the syst...,UB3R-B0T#3802,woah there buttmunch tryin' to cheat the syste...
106634422022860800,"[MaralinaSakura#1304, MaralinaSakura#1304, Mar...","[03-Apr-19 09:50 PM, 03-Apr-19 09:50 PM, 03-Ap...","[:javoShock: I got to think about it, Thanks!,...",MaralinaSakura#1304,":javoShock: I got to think about it,Thanks!,Fa..."
155149108183695360,"[Dyno#3861, Dyno#3861, Dyno#3861, Dyno#3861, D...","[14-Dec-18 03:34 PM, 14-Dec-18 03:35 PM, 07-Ja...","[nan, nan, Wife: Honey I‚Äôm pregnant.\r\n\r\nMe...",Dyno#3861,"nan,nan,Wife: Honey I‚Äôm pregnant.\r\n\r\nMe: W..."
172002275412279296,"[Tatsu#8792, Tatsu#8792, Tatsu#8792, Tatsu#879...","[23-Feb-21 09:15 PM, 25-Feb-21 11:23 PM, 08-Ma...","[nan, nan, nan, > **Viewing server rankings ‚Ä¢ ...",Tatsu#8792,"nan,nan,nan,> **Viewing server rankings ‚Ä¢ [** ..."
173889000015134720,"[faede#0003, faede#0003, faede#0003, faede#000...","[30-Jul-20 01:07 AM, 30-Jul-20 01:08 AM, 30-Ju...",[uhh dskdjdl probably high school story and mi...,faede#0003,uhh dskdjdl probably high school story and mic...
...,...,...,...,...,...
786672447935348737,"[cressidastclaire#3536, cressidastclaire#3536,...","[05-May-21 11:35 AM, 05-May-21 12:21 PM, 05-Ma...","[hello! glad to be here., pig practicals in bi...",cressidastclaire#3536,"hello! glad to be here.,pig practicals in biol..."
806489789574545458,[Hell-Volhard#4976],[18-Apr-21 09:38 PM],"[sure, thanks]",Hell-Volhard#4976,"sure, thanks"
831172293945720852,"[Yume Not.#8543, Yume Not.#8543, Yume Not.#854...","[28-Apr-21 10:22 AM, 28-Apr-21 10:23 AM, 28-Ap...","[Hiiiiiii, And we may or may not regret it lol...",Yume Not.#8543,"Hiiiiiii,And we may or may not regret it lol ü§£..."
873569055733329951,[James Hametson#9998],[12-Aug-21 03:55 PM],[Where‚Äôs the invite to the datamining server a...,James Hametson#9998,Where‚Äôs the invite to the datamining server again
899901520701714493,"[Kaleen Bhaiya#5212, Kaleen Bhaiya#5212, Kalee...","[21-Oct-21 01:46 PM, 21-Oct-21 01:48 PM, 21-Oc...","[that chapter was so boring, not really becaus...",Kaleen Bhaiya#5212,"that chapter was so boring,not really because ..."

In [35]:
new_pcf_gen_common = pcf_gen_common.drop(["Date_x", "Author_x","Content_x"],axis = 1)

In [36]:
new_pcf_gen_common

,Author,Content
AuthorID,,
85614143951892480,UB3R-B0T#3802,woah there buttmunch tryin' to cheat the syste...
106634422022860800,MaralinaSakura#1304,":javoShock: I got to think about it,Thanks!,Fa..."
155149108183695360,Dyno#3861,"nan,nan,Wife: Honey I‚Äôm pregnant.\r\n\r\nMe: W..."
172002275412279296,Tatsu#8792,"nan,nan,nan,> **Viewing server rankings ‚Ä¢ [** ..."
173889000015134720,faede#0003,uhh dskdjdl probably high school story and mic...
...,...,...
786672447935348737,cressidastclaire#3536,"hello! glad to be here.,pig practicals in biol..."
806489789574545458,Hell-Volhard#4976,"sure, thanks"
831172293945720852,Yume Not.#8543,"Hiiiiiii,And we may or may not regret it lol ü§£..."
873569055733329951,James Hametson#9998,Where‚Äôs the invite to the datamining server again
899901520701714493,Kaleen Bhaiya#5212,"that chapter was so boring,not really because ..."

In [37]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.cluster import KMeans

In [38]:
docs = new_pcf_gen_common["Content"].values.astype("U")

In [39]:
vectorizer = TfidfVectorizer(stop_words='english')
features = vectorizer.fit_transform(docs)

In [40]:
k = 10
model = KMeans(n_clusters = k, init = 'k-means++', max_iter= 100,n_init= 1)
model.fit(features)

KMeans(max_iter=100, n_clusters=10, n_init=1)

In [41]:
new_pcf_gen_common['cluster'] = model.labels_

In [42]:
new_pcf_gen_common

,Author,Content,cluster
AuthorID,,,
85614143951892480,UB3R-B0T#3802,woah there buttmunch tryin' to cheat the syste...,2
106634422022860800,MaralinaSakura#1304,":javoShock: I got to think about it,Thanks!,Fa...",4
155149108183695360,Dyno#3861,"nan,nan,Wife: Honey I‚Äôm pregnant.\r\n\r\nMe: W...",6
172002275412279296,Tatsu#8792,"nan,nan,nan,> **Viewing server rankings ‚Ä¢ [** ...",6
173889000015134720,faede#0003,uhh dskdjdl probably high school story and mic...,4
...,...,...,...
786672447935348737,cressidastclaire#3536,"hello! glad to be here.,pig practicals in biol...",4
806489789574545458,Hell-Volhard#4976,"sure, thanks",8
831172293945720852,Yume Not.#8543,"Hiiiiiii,And we may or may not regret it lol ü§£...",4
873569055733329951,James Hametson#9998,Where‚Äôs the invite to the datamining server again,7
899901520701714493,Kaleen Bhaiya#5212,"that chapter was so boring,not really because ...",2

In [43]:
clusters = new_pcf_gen_common.groupby('cluster')

for cluster in clusters.groups:
    f = open('cluster'+str(cluster)+ '.csv', 'w', encoding='utf-8') # create csv file
    data_new = clusters.get_group(cluster)[['Author','Content']] # get title and overview columns
    f.write(data_new.to_csv()) # set index to id
    f.close()

In [44]:
print("Cluster centroids: \n")
order_centroids = model.cluster_centers_.argsort()[:, ::-1]
terms = vectorizer.get_feature_names()

for i in range(k):
    print("Cluster %d:" % i)
    for j in order_centroids[i, :10]:
        print (' %s' % terms[j])
    print('------------')

Cluster centroids:

Cluster 0:
 lmao
 pwease
 uwu
 hyun
 dwew
 kiseki
 ve
 joanne
 https
 fubuki
------------
Cluster 1:
 im
 like
 just
 xd
 dont
 oh
 oof
 yes
 thats
 yeah
------------
Cluster 2:
 https
 com
 morning
 urbanup
 gif
 view
 tenor
 like
 cool
 command
------------
Cluster 3:
 li
 book
 favourite
 favorite
 good
 drewish
 like
 don
 yeah
 favorites
------------
Cluster 4:
 like
 just
 don
 lol
 good
 yeah
 oh
 know
 got
 think
------------
Cluster 5:
 hi
 thank
 yup
 channels
 mal
 lots
 peepowave
 ashton
 server
 oh
------------
Cluster 6:
 nan
 woods
 lee
 hana
 uwu
 doctor
 lives
 hi
 frequency
 whistle
------------
Cluster 7:
 datamining
 invite
 server
 ùôºùöõ
 error
 eruption
 erupted
 erupt
 ertruria
 ers
------------
Cluster 8:
 thanks
 sure
 mod
 cnn
 leitgo65
 plague
 tho
 scn
 hum
 scli
------------
Cluster 9:
 pi
 really
 someday
 beneath
 tom
 oooh
 es
 finished
 late
 life
------------